openapi: 3.0.0
info:
  title: job_offer
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /job_offer:
    get:
      summary: job_offer
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: メッセージ
                  result:
                    title: result_joboffer
                    type: object
                    x-tags:
                      - 求人数の結果
                    properties:
                      broadName:
                        type: string
                        description: 職業大分類1
                      valid_job_offer_number:
                        type: number
                        description: 有効求人数
                      valid_jobfinder:
                        type: number
                        description: 有効就職者
                      finding_employment_count:
                        type: number
                        description: 就職件数
                    x-examples: {}
      operationId: get-job_offer
      parameters:
        - schema:
            type: number
          in: query
          name: prefCode
          description: 都道府県コード
          required: true
        - schema:
            type: number
          in: query
          name: year
          description: 年度
          required: true
        - schema:
            type: number
          in: query
          name: matter
          description: 表示内容
          required: true
        - schema:
            type: number
          in: query
          name: class
          description: 表示分類
          required: true
  /occupation:
    get:
      summary: occupation
      tags: []
      operationId: get-occupation
      parameters:
        - schema:
            type: string
          in: query
          name: iscoCode
          required: true
          description: 職業大分類
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: メッセージ
                  result:
                    title: occupation_middle_category
                    type: object
                    properties:
                      iscoCode:
                        type: string
                        description: 職業大分類コード
                      ismcoCode:
                        type: string
                        description: 職業中分類
                      ismcoName:
                        type: string
                        description: 職業中分類名
  /total_population:
    get:
      summary: total_population
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: メッセージ
                  result:
                    title: result__total_population
                    type: object
                    properties:
                      total_population:
                        type: number
                        description: 総人口
                      bitrh_number:
                        type: number
                        description: 出生数
                      died_number:
                        type: number
                        description: 死亡数
      operationId: get-total_population
      parameters:
        - schema:
            type: number
          in: query
          required: true
          description: 都道府県コード
          name: prefCode
        - schema:
            type: number
          in: query
          name: cityCode
          description: 市区町村コード
          required: true
components:
  schemas: {}
