openapi: 3.0.0
info:
  title: job_offer
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /job_offer:
    get:
      summary: job_offer
      tags: []
      responses: {}
      operationId: get-job_offer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                result:
                  $ref: ../models/nest_2_joboffer.v1.yaml
    post:
      summary: result
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/result_joboffer.v1.yaml
      operationId: post-job_offer
components:
  schemas: {}
