openapi: 3.0.0
info:
  title: job_offer
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /job_offer:
    get:
      summary: job_offer
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: メッセージ
                  result:
                    $ref: ../models/result_joboffer.v1.yaml
      operationId: get-job_offer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  $ref: ../models/request_joboffer.v1.yaml
              required:
                - request
            examples: {}
      parameters: []
  /occupation:
    get:
      summary: occupation
      tags: []
      operationId: get-occupation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                iscoCode:
                  type: string
                  description: 職業大分類
              required:
                - iscoCode
            examples: {}
        description: ''
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: メッセージ
                  result:
                    $ref: ../models/occupation_middle_category.v1.yaml
  /total_population:
    get:
      summary: total_population
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: メッセージ
                  result:
                    $ref: ../models/result_total_population.v1.yaml
      operationId: get-total_population
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  $ref: ../models/request_total_population.v1.yaml
            examples: {}
components:
  schemas: {}
