openapi: 3.0.0
info:
  title: job_offer
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /job_offer:
    get:
      summary: job_offer
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: メッセージ
                  result:
                    $ref: ../models/nest_joboffer.v1.yaml
      operationId: get-job_offer
      parameters:
        - schema:
            type: string
          in: query
          name: prefCode
          description: 都道府県コード
          required: true
        - schema:
            type: string
          in: query
          name: year
          description: 年度
          required: true
        - schema:
            type: string
          in: query
          name: matter
          description: 表示内容
          required: true
        - schema:
            type: string
          in: query
          name: class
          description: 表示分類
          required: true
  /occupation:
    get:
      summary: occupation
      tags: []
      operationId: get-occupation
      parameters:
        - schema:
            type: string
          in: query
          name: iscoCode
          required: true
          description: 職業大分類
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: メッセージ
                  result:
                    $ref: ../models/occupation_middle_category.v1.yaml
  /total_population:
    get:
      summary: total_population
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: メッセージ
                  result:
                    $ref: ../models/result_total_population.v1.yaml
      operationId: get-total_population
      parameters:
        - schema:
            type: string
          in: query
          required: true
          description: 都道府県コード
          name: prefCode
        - schema:
            type: string
          in: query
          name: cityCode
          description: 市区町村コード
          required: true
components:
  schemas: {}
